### ISSUE TITLE
Article model doesn't have the query for the ID

### ISSUE THREAD

**Issue by edwardmagbago** [joomlatools/joomlatools-platform-content#28]
Without this query, specific articles can't be fetched.

**Comment by johanjanssens** [comment]
@raeldc @edwardmagbago Can you give a bit more information about this fix ? Is this a bug in Joomla, or are you implementing a specific use case which would make this a feature ?

**Comment by raeldc** [comment]
@johanjanssens,

This isn't a bug in Joomla. Actually, I think it's something that was removed accidentally during the refactor for Joomlatools Platform. We decided that this should be a hotfix because quite simply, joomlatools-platform-content won't work without this fix since you need to query the id to fetch the article.

**Comment by johanjanssens** [comment]
Great, in that case lets roll out a maintenance release for this.
